sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
env:
  matrix:
    - $COVPYYAML=cov3-default,coveralls3
    - $COVPYYAML=cov4-pyyaml,coveralls4
    - $COVPYYAML=cov3-default,coveralls3
    - $COVPYYAML=cov4-pyyaml,coveralls4
install:
  - pip install tox
  - pip install coveralls
before_script:
  - pip install -r test_requirements.txt
  - git clone https://github.com/kelur/test_for_rdt.git
  - py.test code/HW3_1.py --cov=example
  - cd ..
script:
#   - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d . | sed -e 's/pypypy/pypy/')-$COVPYYAML
  - coverage run --source=test_for_rdt ../HW3_1.py test
after_success:
  - coveralls